services:
  mysql:
    container_name: 'registro-gado'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=registro-gado-db'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'